language: node_js
node_js:
  - '10'
  - '12'
  - '13'
before_script:
  # Remove ./node_modules/.bin from PATH so node-which doesn't replace Unix which and cause RVM to barf. See https://github.com/travis-ci/travis-ci/issues/5092
  - PATH=${PATH//:\.\/node_modules\/\.bin/}
  - rvm install ruby --latest
  - gem install sass scss_lint
script:
  - npm run build
